class ChatMessageRequest {
  const ChatMessageRequest({
    required this.message,
    this.conversationId,
    this.latitude,
    this.longitude,
    this.extra = const {},
  });

  final String message;
  final String? conversationId;
  final double? latitude;
  final double? longitude;
  final Map<String, dynamic> extra;

  factory ChatMessageRequest.fromJson(Map<String, dynamic> json) {
    return ChatMessageRequest(
      message: _asString(json['message']) ?? '',
      conversationId: _asString(_read(json, 'conversation_id', 'conversationId')),
      latitude: _asDouble(json['latitude']),
      longitude: _asDouble(json['longitude']),
      extra: _extra(json, const {'message', 'conversation_id', 'conversationId', 'latitude', 'longitude'}),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      ..._copyMap(extra),
      'message': message,
      if (conversationId != null) 'conversationId': conversationId,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
    };
  }
}

class ChatMessageResponse {
  const ChatMessageResponse({
    required this.conversationId,
    required this.reply,
    this.intent,
    this.confidence,
    this.places = const [],
    this.clinics = const [],
    this.doctors = const [],
    this.route,
    this.suggestions = const [],
    this.extra = const {},
  });

  final String conversationId;
  final String reply;
  final String? intent;
  final double? confidence;
  final List<ChatPlaceResult> places;
  final List<ChatPlaceResult> clinics;
  final List<ChatDoctorResult> doctors;
  final ChatRouteResult? route;
  final List<ChatSuggestion> suggestions;
  final Map<String, dynamic> extra;

  factory ChatMessageResponse.fromJson(Map<String, dynamic> json) {
    final data = _payload(json);
    return ChatMessageResponse(
      conversationId: _asString(_read(data, 'conversation_id', 'conversationId')) ?? '',
      reply: _asString(data['reply']) ?? '',
      intent: _asString(data['intent']),
      confidence: _asDouble(data['confidence']),
      places: _list(data['places']).map(ChatPlaceResult.fromJson).toList(),
      clinics: _list(data['clinics']).map(ChatPlaceResult.fromJson).toList(),
      doctors: _list(data['doctors']).map(ChatDoctorResult.fromJson).toList(),
      route: _asMap(data['route']) == null ? null : ChatRouteResult.fromJson(_asMap(data['route'])!),
      suggestions: _rawList(data['suggestions']).map(ChatSuggestion.fromValue).toList(),
      extra: _extra(data, const {
        'conversation_id',
        'conversationId',
        'reply',
        'intent',
        'confidence',
        'places',
        'clinics',
        'doctors',
        'route',
        'suggestions',
      }),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      ..._copyMap(extra),
      'conversationId': conversationId,
      'reply': reply,
      if (intent != null) 'intent': intent,
      if (confidence != null) 'confidence': confidence,
      'places': places.map((place) => place.toJson()).toList(),
      'clinics': clinics.map((clinic) => clinic.toJson()).toList(),
      'doctors': doctors.map((doctor) => doctor.toJson()).toList(),
      if (route != null) 'route': route!.toJson(),
      'suggestions': suggestions.map((suggestion) => suggestion.toJson()).toList(),
    };
  }
}

class ConversationSummary {
  const ConversationSummary({
    required this.id,
    this.title,
    this.isAutoGenerated,
    this.messageCount,
    this.lastIntent,
    this.hasLocation,
    this.createdAt,
    this.updatedAt,
    this.extra = const {},
  });

  final String id;
  final String? title;
  final bool? isAutoGenerated;
  final int? messageCount;
  final String? lastIntent;
  final bool? hasLocation;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final Map<String, dynamic> extra;

  factory ConversationSummary.fromJson(Map<String, dynamic> json) {
    return ConversationSummary(
      id: _asString(json['id']) ?? '',
      title: _asString(json['title']),
      isAutoGenerated: _asBool(_read(json, 'is_auto_generated', 'isAutoGenerated')),
      messageCount: _asInt(_read(json, 'message_count', 'messageCount')),
      lastIntent: _asString(_read(json, 'last_intent', 'lastIntent')),
      hasLocation: _asBool(_read(json, 'has_location', 'hasLocation')),
      createdAt: _asDate(_read(json, 'created_at', 'createdAt')),
      updatedAt: _asDate(_read(json, 'updated_at', 'updatedAt')),
      extra: _extra(json, const {
        'id',
        'title',
        'is_auto_generated',
        'isAutoGenerated',
        'message_count',
        'messageCount',
        'last_intent',
        'lastIntent',
        'has_location',
        'hasLocation',
        'created_at',
        'createdAt',
        'updated_at',
        'updatedAt',
      }),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      ..._copyMap(extra),
      'id': id,
      if (title != null) 'title': title,
      if (isAutoGenerated != null) 'is_auto_generated': isAutoGenerated,
      if (messageCount != null) 'message_count': messageCount,
      if (lastIntent != null) 'lastIntent': lastIntent,
      if (hasLocation != null) 'hasLocation': hasLocation,
      if (createdAt != null) 'created_at': createdAt!.toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt!.toIso8601String(),
    };
  }
}

class ConversationDetail {
  const ConversationDetail({
    this.conversation,
    this.messages = const [],
    this.places = const [],
    this.messageCount,
    this.extra = const {},
  });

  final ConversationSummary? conversation;
  final List<ChatMessage> messages;
  final List<ChatConversationPlace> places;
  final int? messageCount;
  final Map<String, dynamic> extra;

  factory ConversationDetail.fromJson(Map<String, dynamic> json) {
    final data = _payload(json);
    final conversation = _asMap(data['conversation']);
    return ConversationDetail(
      conversation: conversation == null ? null : ConversationSummary.fromJson(conversation),
      messages: _list(data['messages']).map(ChatMessage.fromJson).toList(),
      places: _list(data['places']).map(ChatConversationPlace.fromJson).toList(),
      messageCount: _asInt(_read(data, 'message_count', 'messageCount')),
      extra: _extra(data, const {'conversation', 'messages', 'places', 'message_count', 'messageCount'}),
    );
  }
}

class ChatMessage {
  const ChatMessage({
    required this.id,
    this.conversationId,
    required this.messageText,
    required this.messageType,
    this.confidenceScore,
    this.metadata = const ChatMetadata(),
    this.createdAt,
    this.entities = const {},
    this.conversationContext = const {},
    this.lastIntent,
    this.hasLocation,
    this.extra = const {},
  });

  final String id;
  final String? conversationId;
  final String messageText;
  final String messageType;
  final double? confidenceScore;
  final ChatMetadata metadata;
  final DateTime? createdAt;
  final Map<String, dynamic> entities;
  final Map<String, dynamic> conversationContext;
  final String? lastIntent;
  final bool? hasLocation;
  final Map<String, dynamic> extra;

  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    return ChatMessage(
      id: _asString(json['id']) ?? '',
      conversationId: _asString(_read(json, 'conversation_id', 'conversationId')),
      messageText: _asString(_read(json, 'message_text', 'messageText')) ?? _asString(json['message']) ?? '',
      messageType: _asString(_read(json, 'message_type', 'messageType')) ?? '',
      confidenceScore: _asDouble(_read(json, 'confidence_score', 'confidenceScore')),
      metadata: ChatMetadata.fromJson(_asMap(json['metadata']) ?? const {}),
      createdAt: _asDate(_read(json, 'created_at', 'createdAt')),
      entities: _asMap(json['entities']) ?? const {},
      conversationContext: _asMap(_read(json, 'conversation_context', 'conversationContext')) ?? const {},
      lastIntent: _asString(_read(json, 'last_intent', 'lastIntent')),
      hasLocation: _asBool(_read(json, 'has_location', 'hasLocation')),
      extra: _extra(json, const {
        'id',
        'conversation_id',
        'conversationId',
        'message_text',
        'messageText',
        'message',
        'message_type',
        'messageType',
        'confidence_score',
        'confidenceScore',
        'metadata',
        'created_at',
        'createdAt',
        'entities',
        'conversation_context',
        'conversationContext',
        'last_intent',
        'lastIntent',
        'has_location',
        'hasLocation',
      }),
    );
  }
}

class ChatPlaceResult {
  const ChatPlaceResult({
    required this.id,
    this.nameAr,
    this.nameEn,
    this.addressAr,
    this.addressEn,
    this.city,
    this.region,
    this.latitude,
    this.longitude,
    this.distanceKm,
    this.phone,
    this.type,
    this.metadata = const ChatMetadata(),
    this.extra = const {},
  });

  final String id;
  final String? nameAr;
  final String? nameEn;
  final String? addressAr;
  final String? addressEn;
  final String? city;
  final String? region;
  final double? latitude;
  final double? longitude;
  final double? distanceKm;
  final String? phone;
  final String? type;
  final ChatMetadata metadata;
  final Map<String, dynamic> extra;

  factory ChatPlaceResult.fromJson(Map<String, dynamic> json) {
    return ChatPlaceResult(
      id: _asString(json['id']) ?? '',
      nameAr: _asString(_read(json, 'name_ar', 'nameAr')),
      nameEn: _asString(_read(json, 'name_en', 'nameEn')) ?? _asString(json['name']),
      addressAr: _asString(_read(json, 'address_ar', 'addressAr')),
      addressEn: _asString(_read(json, 'address_en', 'addressEn')) ?? _asString(json['address']),
      city: _asString(json['city']),
      region: _asString(json['region']),
      latitude: _asDouble(json['latitude']),
      longitude: _asDouble(json['longitude']),
      distanceKm: _asDouble(_read(json, 'distance_km', 'distanceKm')),
      phone: _asString(json['phone']),
      type: _asString(json['type']),
      metadata: ChatMetadata.fromJson(_asMap(json['metadata']) ?? const {}),
      extra: _extra(json, const {
        'id',
        'name_ar',
        'nameAr',
        'name_en',
        'nameEn',
        'name',
        'address_ar',
        'addressAr',
        'address_en',
        'addressEn',
        'address',
        'city',
        'region',
        'latitude',
        'longitude',
        'distance_km',
        'distanceKm',
        'phone',
        'type',
        'metadata',
      }),
    );
  }

  Map<String, dynamic> toJson() => {
    ..._copyMap(extra),
    'id': id,
    if (nameAr != null) 'name_ar': nameAr,
    if (nameEn != null) 'name_en': nameEn,
    if (addressAr != null) 'address_ar': addressAr,
    if (addressEn != null) 'address_en': addressEn,
    if (city != null) 'city': city,
    if (region != null) 'region': region,
    if (latitude != null) 'latitude': latitude,
    if (longitude != null) 'longitude': longitude,
    if (distanceKm != null) 'distance_km': distanceKm,
    if (phone != null) 'phone': phone,
    if (type != null) 'type': type,
    if (metadata.values.isNotEmpty) 'metadata': metadata.toJson(),
  };
}

class ChatDoctorResult {
  const ChatDoctorResult({
    required this.id,
    this.firstNameAr,
    this.lastNameAr,
    this.firstNameEn,
    this.lastNameEn,
    this.specialtyAr,
    this.specialtyEn,
    this.averageRating,
    this.consultationFee,
    this.clinicId,
    this.clinicNameAr,
    this.clinicNameEn,
    this.metadata = const ChatMetadata(),
    this.extra = const {},
  });

  final String id;
  final String? firstNameAr;
  final String? lastNameAr;
  final String? firstNameEn;
  final String? lastNameEn;
  final String? specialtyAr;
  final String? specialtyEn;
  final double? averageRating;
  final double? consultationFee;
  final String? clinicId;
  final String? clinicNameAr;
  final String? clinicNameEn;
  final ChatMetadata metadata;
  final Map<String, dynamic> extra;

  factory ChatDoctorResult.fromJson(Map<String, dynamic> json) {
    return ChatDoctorResult(
      id: _asString(json['id']) ?? '',
      firstNameAr: _asString(_read(json, 'first_name_ar', 'firstNameAr')),
      lastNameAr: _asString(_read(json, 'last_name_ar', 'lastNameAr')),
      firstNameEn: _asString(_read(json, 'first_name_en', 'firstNameEn')),
      lastNameEn: _asString(_read(json, 'last_name_en', 'lastNameEn')),
      specialtyAr: _asString(_read(json, 'specialty_ar', 'specialtyAr')),
      specialtyEn: _asString(_read(json, 'specialty_en', 'specialtyEn')),
      averageRating: _asDouble(_read(json, 'average_rating', 'averageRating')),
      consultationFee: _asDouble(_read(json, 'consultation_fee', 'consultationFee')),
      clinicId: _asString(_read(json, 'clinic_id', 'clinicId')),
      clinicNameAr: _asString(_read(json, 'clinic_name_ar', 'clinicNameAr')),
      clinicNameEn: _asString(_read(json, 'clinic_name_en', 'clinicNameEn')),
      metadata: ChatMetadata.fromJson(_asMap(json['metadata']) ?? const {}),
      extra: _extra(json, const {
        'id',
        'first_name_ar',
        'firstNameAr',
        'last_name_ar',
        'lastNameAr',
        'first_name_en',
        'firstNameEn',
        'last_name_en',
        'lastNameEn',
        'specialty_ar',
        'specialtyAr',
        'specialty_en',
        'specialtyEn',
        'average_rating',
        'averageRating',
        'consultation_fee',
        'consultationFee',
        'clinic_id',
        'clinicId',
        'clinic_name_ar',
        'clinicNameAr',
        'clinic_name_en',
        'clinicNameEn',
        'metadata',
      }),
    );
  }

  Map<String, dynamic> toJson() => {
    ..._copyMap(extra),
    'id': id,
    if (firstNameAr != null) 'first_name_ar': firstNameAr,
    if (lastNameAr != null) 'last_name_ar': lastNameAr,
    if (firstNameEn != null) 'first_name_en': firstNameEn,
    if (lastNameEn != null) 'last_name_en': lastNameEn,
    if (specialtyAr != null) 'specialty_ar': specialtyAr,
    if (specialtyEn != null) 'specialty_en': specialtyEn,
    if (averageRating != null) 'average_rating': averageRating,
    if (consultationFee != null) 'consultation_fee': consultationFee,
    if (clinicId != null) 'clinic_id': clinicId,
    if (clinicNameAr != null) 'clinic_name_ar': clinicNameAr,
    if (clinicNameEn != null) 'clinic_name_en': clinicNameEn,
    if (metadata.values.isNotEmpty) 'metadata': metadata.toJson(),
  };
}

class ChatRouteResult {
  const ChatRouteResult({this.distanceKm, this.durationMinutes, this.polyline, this.extra = const {}});

  final double? distanceKm;
  final int? durationMinutes;
  final String? polyline;
  final Map<String, dynamic> extra;

  factory ChatRouteResult.fromJson(Map<String, dynamic> json) {
    return ChatRouteResult(
      distanceKm: _asDouble(_read(json, 'distance_km', 'distanceKm')),
      durationMinutes: _asInt(_read(json, 'duration_minutes', 'durationMinutes')),
      polyline: _asString(json['polyline']),
      extra: _extra(json, const {'distance_km', 'distanceKm', 'duration_minutes', 'durationMinutes', 'polyline'}),
    );
  }

  Map<String, dynamic> toJson() => {
    ..._copyMap(extra),
    if (distanceKm != null) 'distance_km': distanceKm,
    if (durationMinutes != null) 'duration_minutes': durationMinutes,
    if (polyline != null) 'polyline': polyline,
  };
}

class ChatSuggestion {
  const ChatSuggestion({required this.text, this.id, this.type, this.metadata = const ChatMetadata(), this.extra = const {}});

  final String? id;
  final String text;
  final String? type;
  final ChatMetadata metadata;
  final Map<String, dynamic> extra;

  factory ChatSuggestion.fromJson(Map<String, dynamic> json) {
    return ChatSuggestion(
      id: _asString(json['id']),
      text: _asString(json['text']) ?? _asString(json['label']) ?? '',
      type: _asString(json['type']),
      metadata: ChatMetadata.fromJson(_asMap(json['metadata']) ?? const {}),
      extra: _extra(json, const {'id', 'text', 'label', 'type', 'metadata'}),
    );
  }

  factory ChatSuggestion.fromValue(Object? value) {
    if (value is Map) {
      return ChatSuggestion.fromJson(Map<String, dynamic>.from(value));
    }
    return ChatSuggestion(text: _asString(value) ?? '');
  }

  Map<String, dynamic> toJson() => {
    ..._copyMap(extra),
    if (id != null) 'id': id,
    'text': text,
    if (type != null) 'type': type,
    if (metadata.values.isNotEmpty) 'metadata': metadata.toJson(),
  };
}

class ChatConversationPlace extends ChatPlaceResult {
  const ChatConversationPlace({
    required super.id,
    super.nameAr,
    super.nameEn,
    super.addressAr,
    super.addressEn,
    super.city,
    super.region,
    super.latitude,
    super.longitude,
    super.distanceKm,
    super.phone,
    super.type,
    super.metadata,
    super.extra,
  });

  factory ChatConversationPlace.fromJson(Map<String, dynamic> json) {
    final place = ChatPlaceResult.fromJson(json);
    return ChatConversationPlace(
      id: place.id,
      nameAr: place.nameAr,
      nameEn: place.nameEn,
      addressAr: place.addressAr,
      addressEn: place.addressEn,
      city: place.city,
      region: place.region,
      latitude: place.latitude,
      longitude: place.longitude,
      distanceKm: place.distanceKm,
      phone: place.phone,
      type: place.type,
      metadata: place.metadata,
      extra: place.extra,
    );
  }
}

class ChatPagination {
  const ChatPagination({this.page, this.limit, this.total, this.totalPages, this.hasNext, this.hasPrevious, this.extra = const {}});

  final int? page;
  final int? limit;
  final int? total;
  final int? totalPages;
  final bool? hasNext;
  final bool? hasPrevious;
  final Map<String, dynamic> extra;

  factory ChatPagination.fromJson(Map<String, dynamic> json) {
    return ChatPagination(
      page: _asInt(json['page']),
      limit: _asInt(json['limit']),
      total: _asInt(json['total']),
      totalPages: _asInt(_read(json, 'total_pages', 'totalPages')),
      hasNext: _asBool(_read(json, 'has_next', 'hasNext')),
      hasPrevious: _asBool(_read(json, 'has_previous', 'hasPrevious')),
      extra: _extra(json, const {'page', 'limit', 'total', 'total_pages', 'totalPages', 'has_next', 'hasNext', 'has_previous', 'hasPrevious'}),
    );
  }
}

class ChatMetadata {
  const ChatMetadata([this.values = const {}]);

  final Map<String, dynamic> values;

  double? get latitude => _asDouble(values['latitude']);
  double? get longitude => _asDouble(values['longitude']);

  factory ChatMetadata.fromJson(Map<String, dynamic> json) => ChatMetadata(_copyMap(json));

  Map<String, dynamic> toJson() => _copyMap(values);
}

Map<String, dynamic> _payload(Map<String, dynamic> json) => _asMap(json['data']) ?? json;

Object? _read(Map<String, dynamic> json, String snake, String camel) => json.containsKey(snake) ? json[snake] : json[camel];

Map<String, dynamic>? _asMap(Object? value) => value is Map ? Map<String, dynamic>.from(value) : null;

List<Map<String, dynamic>> _list(Object? value) {
  if (value is! List) return const [];
  return value.whereType<Map>().map((item) => Map<String, dynamic>.from(item)).toList();
}

List<Object?> _rawList(Object? value) => value is List ? List<Object?>.from(value) : const [];

String? _asString(Object? value) => value?.toString();

double? _asDouble(Object? value) {
  if (value is num) return value.toDouble();
  if (value is String) return double.tryParse(value);
  return null;
}

int? _asInt(Object? value) {
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) return int.tryParse(value);
  return null;
}

bool? _asBool(Object? value) {
  if (value is bool) return value;
  if (value is String) {
    if (value == '1') return true;
    if (value == '0') return false;
    return bool.tryParse(value);
  }
  if (value is num) return value != 0;
  return null;
}

DateTime? _asDate(Object? value) => value == null ? null : DateTime.tryParse(value.toString());

Map<String, dynamic> _extra(Map<String, dynamic> json, Set<String> known) {
  return _copyMap(Map<String, dynamic>.fromEntries(json.entries.where((entry) => !known.contains(entry.key))));
}

Map<String, dynamic> _copyMap(Map<String, dynamic> value) {
  return value.map((key, item) => MapEntry(key, _copyValue(item)));
}

Object? _copyValue(Object? value) {
  if (value is Map) return _copyMap(Map<String, dynamic>.from(value));
  if (value is List) return value.map(_copyValue).toList();
  return value;
}
