const ContactPage=(()=>{
    const byId=id=>document.getElementById(id),isAr=()=>I18n.getLang()==='ar';
    function setText(id,ar,en){byId(id).textContent=isAr()?ar:en;}
    function localize(){const copy={contactTitle:['تواصل معنا','Contact Us'],contactSubtitle:['أرسل رسالة دعم آمنة إلى فريق إدارة MedOrbit.','Send a secure support message to the MedOrbit administration team.'],contactNameLabel:['الاسم','Name'],contactEmailLabel:['البريد الإلكتروني','Email'],contactSubjectLabel:['الموضوع','Subject'],contactMessageLabel:['الرسالة','Message'],contactMessageHelp:['لا تدرج كلمات مرور أو رموز وصول أو تفاصيل طبية غير ضرورية.','Do not include passwords, tokens, or unnecessary medical details.'],sendContactLabel:['إرسال الرسالة','Send message'],contactHelpTitle:['كيف يمكننا المساعدة','How we can help'],contactSafeTitle:['معالجة آمنة','Handled securely'],contactSafeCopy:['يمكن للمسؤولين المخولين فقط فتح رسائل التواصل.','Only authorized administrators can open contact messages.'],contactNotifyTitle:['توجيه سريع','Routed promptly'],contactNotifyCopy:['يتلقى المسؤولون النشطون إشعاراً آمناً من دون نص رسالتك.','Active administrators receive a safe notification without your message body.']};Object.entries(copy).forEach(([id,v])=>setText(id,v[0],v[1]));}
    function feedback(message,type){const node=byId('contactFeedback');node.textContent=message;node.className=`page-feedback ${type}`;}
    async function submit(event){event.preventDefault();const button=byId('sendContact');button.disabled=true;try{const body={subject:byId('contactSubject').value,message:byId('contactMessage').value};if(!API.isAuthenticated()){body.name=byId('contactName').value;body.email=byId('contactEmail').value;}await API.contact.submit(body);byId('contactForm').reset();byId('guestIdentityFields').classList.toggle('hidden',API.isAuthenticated());feedback(isAr()?'وصلت رسالتك إلى فريق الإدارة.':'Your message reached the administration team.','success');}catch(err){feedback(err.message||(isAr()?'تعذر إرسال الرسالة.':'Unable to send message.'),'error');}finally{button.disabled=false;}}
    function init(){localize();byId('guestIdentityFields').classList.toggle('hidden',API.isAuthenticated());window.addEventListener('languageChanged',localize);byId('contactForm').addEventListener('submit',submit);}
    return{init};
})();
