const crypto=require('crypto');
const {Pool}=require('pg');
const {poolConfig,apiBase}=require('./helpers/test-environment');
const {enqueueOutboxEvent}=require('../src/services/outbox.service');
const {OutboxPublisher}=require('../src/workers/outboxPublisher');
const {observeEvent}=require('../src/workers/eventObserver');
const {validateEnvelope}=require('../src/events/eventEnvelope');
const {decide}=require('../src/services/doctorApplication.service');
const {ensureActiveCareRelationship}=require('../src/services/careRelationship.service');
const messaging=require('../src/services/messaging.service');

const pool=new Pool(poolConfig),marker=`S7${String(Date.now()).slice(-8)}`,users=[],outboxIds=[],processedIds=[];
let specialtyId=null,passed=0,failed=0;
function check(name,ok,detail=''){if(ok){passed++;console.log(`  ✓ ${name}`);}else{failed++;console.error(`  ✗ ${name}${detail?` — ${detail}`:''}`);}}
async function user(key,role='patient',withPatient=role==='patient'){
 const item={id:crypto.randomUUID(),email:`${marker}_${key}@medorbit.test`,role};users.push(item.id);
 await pool.query(`INSERT INTO medorbit.users(id,email,password_hash,role,is_active,email_verified,authorization_version) VALUES($1,$2,'s7-test',$3,true,true,1)`,[item.id,item.email,role]);
 await pool.query(`INSERT INTO medorbit.user_profiles(user_id,first_name_ar,last_name_ar,first_name_en,last_name_en) VALUES($1,'اختبار','أحداث',$2,'Events')`,[item.id,key]);
 if(withPatient){item.patientId=crypto.randomUUID();await pool.query(`INSERT INTO medorbit.patients(id,user_id) VALUES($1,$2)`,[item.patientId,item.id]);}return item;
}
async function doctor(key){const item=await user(key,'doctor',true);item.doctorId=crypto.randomUUID();await pool.query(`INSERT INTO medorbit.doctors(id,user_id,medical_license_number,approval_status,approved_at) VALUES($1,$2,$3,'approved',NOW())`,[item.doctorId,item.id,`${marker}-${key}`]);return item;}
async function txEvent({aggregateId=crypto.randomUUID(),eventType='test.domain.changed',headers={testRun:marker},payload={state:'changed'}}={}){const client=await pool.connect();try{await client.query('BEGIN');const row=await enqueueOutboxEvent(client,{aggregateType:'test_entity',aggregateId,eventType,payload,headers});await client.query('COMMIT');outboxIds.push(row.id);return row;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
class FakeProducer{constructor(){this.sent=[];this.fail=false;this.connected=false;}async connect(){this.connected=true;}async disconnect(){this.connected=false;}async send(record){if(this.fail)throw new Error('token=hidden broker unavailable');this.sent.push(record);return[{}];}}
async function remember(query,params=[]){const rows=(await pool.query(query,params)).rows;for(const row of rows)if(!outboxIds.includes(row.id))outboxIds.push(row.id);return rows;}
async function cleanup(){
 await pool.query('DROP TRIGGER IF EXISTS s7_force_outbox_failure ON medorbit.outbox_events').catch(()=>{});await pool.query('DROP FUNCTION IF EXISTS medorbit.s7_force_outbox_failure()').catch(()=>{});
 await pool.query('DROP TRIGGER IF EXISTS s7_force_consumer_failure ON medorbit.processed_events').catch(()=>{});await pool.query('DROP FUNCTION IF EXISTS medorbit.s7_force_consumer_failure()').catch(()=>{});
 if(processedIds.length)await pool.query(`DELETE FROM medorbit.processed_events WHERE event_id=ANY($1::uuid[])`,[processedIds]).catch(()=>{});
 if(outboxIds.length)await pool.query(`DELETE FROM medorbit.outbox_events WHERE id=ANY($1::uuid[])`,[outboxIds]).catch(()=>{});
 if(users.length){
  await pool.query(`DELETE FROM medorbit.audit_logs WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});await pool.query(`DELETE FROM medorbit.notifications WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});await pool.query(`DELETE FROM medorbit.user_events WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});
  await pool.query(`DELETE FROM medorbit.direct_conversations WHERE relationship_id IN(SELECT id FROM medorbit.doctor_patient_relationships WHERE doctor_id IN(SELECT id FROM medorbit.doctors WHERE user_id=ANY($1::uuid[])) OR patient_id IN(SELECT id FROM medorbit.patients WHERE user_id=ANY($1::uuid[])))`,[users]).catch(()=>{});
  await pool.query(`DELETE FROM medorbit.doctor_patient_relationships WHERE doctor_id IN(SELECT id FROM medorbit.doctors WHERE user_id=ANY($1::uuid[])) OR patient_id IN(SELECT id FROM medorbit.patients WHERE user_id=ANY($1::uuid[]))`,[users]).catch(()=>{});
  await pool.query(`DELETE FROM medorbit.doctor_applications WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});await pool.query(`DELETE FROM medorbit.doctors WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});await pool.query(`DELETE FROM medorbit.patients WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});await pool.query(`DELETE FROM medorbit.user_profiles WHERE user_id=ANY($1::uuid[])`,[users]).catch(()=>{});await pool.query(`DELETE FROM medorbit.users WHERE id=ANY($1::uuid[])`,[users]).catch(()=>{});
 }
 if(specialtyId)await pool.query(`DELETE FROM medorbit.specialties WHERE id=$1`,[specialtyId]).catch(()=>{});
}

(async()=>{console.log('\nS7 transactional outbox and Kafka foundation tests\n');try{
 check('test isolation targets Docker test database',poolConfig.host==='postgres'&&poolConfig.database.endsWith('_test')&&process.env.MEDORBIT_TEST_ISOLATION==='docker');
 const applicant=await user('applicant'),patient=await user('patient'),admin=await user('admin','admin',false),doc=await doctor('doctor');specialtyId=crypto.randomUUID();
 await pool.query(`INSERT INTO medorbit.specialties(id,name_ar,name_en) VALUES($1,$2,$3)`,[specialtyId,`${marker} تخصص`,`${marker} Specialty`]);

 const beforeName=(await pool.query(`SELECT first_name_en FROM medorbit.user_profiles WHERE user_id=$1`,[patient.id])).rows[0].first_name_en;
 const commitClient=await pool.connect();let committed;try{await commitClient.query('BEGIN');await commitClient.query(`UPDATE medorbit.user_profiles SET first_name_en=$2 WHERE user_id=$1`,[patient.id,'Committed']);committed=await enqueueOutboxEvent(commitClient,{aggregateType:'test_entity',aggregateId:patient.id,eventType:'test.domain.committed',payload:{userId:patient.id,state:'committed'},headers:{testRun:marker}});await commitClient.query('COMMIT');}finally{commitClient.release();}outboxIds.push(committed.id);
 check('domain mutation and outbox commit together',(await pool.query(`SELECT first_name_en FROM medorbit.user_profiles WHERE user_id=$1`,[patient.id])).rows[0].first_name_en==='Committed'&&Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events WHERE id=$1`,[committed.id])).rows[0].count)===1);
 const rollbackClient=await pool.connect();const rollbackId=crypto.randomUUID();try{await rollbackClient.query('BEGIN');await rollbackClient.query(`UPDATE medorbit.user_profiles SET first_name_en='RolledBack' WHERE user_id=$1`,[patient.id]);const row=await enqueueOutboxEvent(rollbackClient,{eventId:rollbackId,aggregateType:'test_entity',aggregateId:patient.id,eventType:'test.domain.rolled_back',payload:{state:'rollback'},headers:{testRun:marker}});outboxIds.push(row.id);await rollbackClient.query('ROLLBACK');}finally{rollbackClient.release();}
 check('explicit transaction rollback removes mutation and outbox',(await pool.query(`SELECT first_name_en FROM medorbit.user_profiles WHERE user_id=$1`,[patient.id])).rows[0].first_name_en==='Committed'&&Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events WHERE id=$1`,[rollbackId])).rows[0].count)===0);
 await pool.query(`CREATE FUNCTION medorbit.s7_force_outbox_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.headers->>'forceFail'='true' THEN RAISE EXCEPTION 'controlled outbox failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER s7_force_outbox_failure BEFORE INSERT ON medorbit.outbox_events FOR EACH ROW EXECUTE FUNCTION medorbit.s7_force_outbox_failure()`);
 const failedClient=await pool.connect();let insertFailed=false;try{await failedClient.query('BEGIN');await failedClient.query(`UPDATE medorbit.user_profiles SET first_name_en='MustRollback' WHERE user_id=$1`,[patient.id]);await enqueueOutboxEvent(failedClient,{aggregateType:'test_entity',aggregateId:patient.id,eventType:'test.domain.must_rollback',payload:{state:'x'},headers:{forceFail:'true'}});await failedClient.query('COMMIT');}catch{insertFailed=true;await failedClient.query('ROLLBACK');}finally{failedClient.release();}
 check('outbox insert failure rolls back domain mutation',insertFailed&&(await pool.query(`SELECT first_name_en FROM medorbit.user_profiles WHERE user_id=$1`,[patient.id])).rows[0].first_name_en==='Committed');
 await pool.query('DROP TRIGGER s7_force_outbox_failure ON medorbit.outbox_events; DROP FUNCTION medorbit.s7_force_outbox_failure()');
 const domainFailClient=await pool.connect();const countBefore=Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events`)).rows[0].count);try{await domainFailClient.query('BEGIN');throw new Error('domain failure');}catch{await domainFailClient.query('ROLLBACK');}finally{domainFailClient.release();}
 check('domain failure creates no outbox row',Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events`)).rows[0].count)===countBefore);
 check('event id is stable UUID and version stored',committed.id&&committed.event_version===1&&committed.id===String(committed.id));
 let privacyRejected=false;try{const c=await pool.connect();try{await c.query('BEGIN');await enqueueOutboxEvent(c,{aggregateType:'test_entity',eventType:'test.unsafe',payload:{messageBody:'secret'}});}finally{await c.query('ROLLBACK');c.release();}}catch{privacyRejected=true;}check('privacy guard rejects message bodies',privacyRejected);
 await pool.query(`DELETE FROM medorbit.outbox_events WHERE id=ANY($1::uuid[])`,[outboxIds]);outboxIds.length=0;

 const applicationId=crypto.randomUUID();await pool.query(`INSERT INTO medorbit.doctor_applications(id,user_id,specialty_id,medical_license_number) VALUES($1,$2,$3,$4)`,[applicationId,applicant.id,specialtyId,`${marker}-APP`]);
 await decide(applicationId,{sub:admin.id,role:'admin'},true);const doctorEvent=(await remember(`SELECT * FROM medorbit.outbox_events WHERE aggregate_id=$1`,[applicationId]))[0];
 check('doctor approval writes one transactional outbox event',doctorEvent?.event_type==='doctor.application.approved');check('doctor approval payload is safe IDs/state only',Object.keys(doctorEvent.payload).sort().join(',')==='applicationId,doctorId,reviewerId,status,userId'&&!JSON.stringify(doctorEvent.payload).includes('license'));
 let secondApprovalFailed=false;try{await decide(applicationId,{sub:admin.id,role:'admin'},true);}catch{secondApprovalFailed=true;}check('duplicate doctor approval creates no duplicate event',secondApprovalFailed&&Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events WHERE aggregate_id=$1`,[applicationId])).rows[0].count)===1);

 const careClient=await pool.connect();let relationship;try{await careClient.query('BEGIN');relationship=(await ensureActiveCareRelationship({doctorId:doc.doctorId,patientId:patient.patientId,source:'manual_assign',actorUserId:admin.id,actorRole:'admin'},careClient)).relationship;await careClient.query('COMMIT');}finally{careClient.release();}
 const careEvent=(await remember(`SELECT * FROM medorbit.outbox_events WHERE aggregate_id=$1`,[relationship.id]))[0];check('care relationship creation writes outbox event',careEvent?.event_type==='care.relationship.created');
 const careClient2=await pool.connect();try{await careClient2.query('BEGIN');await ensureActiveCareRelationship({doctorId:doc.doctorId,patientId:patient.patientId,source:'manual_assign',actorUserId:admin.id,actorRole:'admin'},careClient2);await careClient2.query('COMMIT');}finally{careClient2.release();}check('idempotent care ensure creates one logical event',Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events WHERE aggregate_id=$1`,[relationship.id])).rows[0].count)===1);

 const conversationId=crypto.randomUUID();await pool.query(`INSERT INTO medorbit.direct_conversations(id,relationship_id) VALUES($1,$2)`,[conversationId,relationship.id]);await pool.query(`INSERT INTO medorbit.conversation_members(conversation_id,user_id,member_role) VALUES($1,$2,'patient'),($1,$3,'doctor')`,[conversationId,patient.id,doc.id]);
 const clientMessageId=crypto.randomUUID(),messageResult=await messaging.sendMessage({conversationId,userId:patient.id,body:`private ${marker}`,clientMessageId});const messageEvent=(await remember(`SELECT * FROM medorbit.outbox_events WHERE aggregate_id=$1`,[messageResult.message.id]))[0];
 check('direct message writes transactional outbox event',messageEvent?.event_type==='direct.message.sent');const messagePayload=JSON.stringify(messageEvent.payload);check('direct message event excludes body and clinical data',!messagePayload.includes(marker)&&!/(body|content|clinical|diagnosis)/i.test(messagePayload));
 await messaging.sendMessage({conversationId,userId:patient.id,body:`private ${marker}`,clientMessageId});check('idempotent message retry creates one logical event',Number((await pool.query(`SELECT count(*) FROM medorbit.outbox_events WHERE aggregate_id=$1`,[messageResult.message.id])).rows[0].count)===1);
 check('existing user_events and audit_logs remain active',Number((await pool.query(`SELECT count(*) FROM medorbit.user_events WHERE user_id=ANY($1::uuid[])`,[users])).rows[0].count)>0&&Number((await pool.query(`SELECT count(*) FROM medorbit.audit_logs WHERE user_id=ANY($1::uuid[])`,[users])).rows[0].count)>0);
 await pool.query(`DELETE FROM medorbit.outbox_events WHERE id=ANY($1::uuid[])`,[outboxIds]);outboxIds.length=0;

 const producer=new FakeProducer(),successRow=await txEvent();const publisher=new OutboxPublisher({pool,producer,workerId:`${marker}-publisher`,batchSize:1});await publisher.connect();check('Kafka producer connects explicitly',producer.connected);check('pending row is claimed',await publisher.runOnce()===1);check('successful publish marks published',(await pool.query(`SELECT status,published_at FROM medorbit.outbox_events WHERE id=$1`,[successRow.id])).rows[0].status==='published');check('published row is not republished',await publisher.runOnce()===0&&producer.sent.length===1);
 const failRow=await txEvent(),failing=new FakeProducer();failing.fail=true;const failPublisher=new OutboxPublisher({pool,producer:failing,workerId:`${marker}-fail`,batchSize:1,maxAttempts:3});await failPublisher.runOnce();let failedRow=(await pool.query(`SELECT * FROM medorbit.outbox_events WHERE id=$1`,[failRow.id])).rows[0];check('Kafka failure marks failed and increments attempts',failedRow.status==='failed'&&failedRow.attempt_count===1);check('retry available_at moves forward',new Date(failedRow.available_at)>new Date(failedRow.updated_at));check('last_error is bounded and sanitized',!failedRow.last_error.includes('hidden')&&failedRow.last_error.length<=500);
 failing.fail=false;await pool.query(`UPDATE medorbit.outbox_events SET available_at=NOW() WHERE id=$1`,[failRow.id]);await failPublisher.runOnce();check('successful retry later publishes',(await pool.query(`SELECT status FROM medorbit.outbox_events WHERE id=$1`,[failRow.id])).rows[0].status==='published');
 const concurrentA=await txEvent(),concurrentB=await txEvent(),p1=new OutboxPublisher({pool,producer:new FakeProducer(),workerId:`${marker}-w1`,batchSize:1}),p2=new OutboxPublisher({pool,producer:new FakeProducer(),workerId:`${marker}-w2`,batchSize:1});const[claims1,claims2]=await Promise.all([p1.claimBatch(),p2.claimBatch()]);check('two workers claim distinct rows',claims1.length===1&&claims2.length===1&&claims1[0].id!==claims2[0].id);await p1.publishRow(claims1[0]);await p2.publishRow(claims2[0]);
 const stale=await txEvent();await pool.query(`UPDATE medorbit.outbox_events SET status='publishing',locked_at=NOW()-interval '10 minutes',locked_by='dead-worker' WHERE id=$1`,[stale.id]);const stalePub=new OutboxPublisher({pool,producer:new FakeProducer(),workerId:`${marker}-recover`,batchSize:1,lockTimeoutMs:5000});check('stale publishing lock is reclaimed',(await stalePub.claimBatch())[0]?.id===stale.id);await stalePub.publishRow((await pool.query(`SELECT * FROM medorbit.outbox_events WHERE id=$1`,[stale.id])).rows[0]);
 const dead=await txEvent(),deadProducer=new FakeProducer();deadProducer.fail=true;await new OutboxPublisher({pool,producer:deadProducer,workerId:`${marker}-dead`,batchSize:1,maxAttempts:1}).runOnce();check('max attempts transitions row to dead',(await pool.query(`SELECT status FROM medorbit.outbox_events WHERE id=$1`,[dead.id])).rows[0].status==='dead');

 const duplicate=await txEvent(),duplicateProducer=new FakeProducer(),crashPublisher=new OutboxPublisher({pool,producer:duplicateProducer,workerId:`${marker}-crash`,batchSize:1,afterPublish:async()=>{throw new Error('crash after publish');}});await crashPublisher.runOnce();await pool.query(`UPDATE medorbit.outbox_events SET available_at=NOW() WHERE id=$1`,[duplicate.id]);await new OutboxPublisher({pool,producer:duplicateProducer,workerId:`${marker}-retry`,batchSize:1}).runOnce();const delivered=duplicateProducer.sent.map(record=>JSON.parse(record.messages[0].value));check('at-least-once retry can deliver duplicate with stable event id',delivered.length===2&&delivered[0].eventId===delivered[1].eventId);
 const envelope=delivered[0];processedIds.push(envelope.eventId);const firstObserved=await observeEvent(`${marker}-observer`,envelope,pool),secondObserved=await observeEvent(`${marker}-observer`,envelope,pool),otherObserved=await observeEvent(`${marker}-observer-2`,envelope,pool);check('consumer records valid event once',firstObserved.processed&&!secondObserved.processed);check('second consumer independently processes same event',otherObserved.processed);
 let malformed=false,unsupported=false;try{validateEnvelope({});}catch{malformed=true;}try{validateEnvelope({...envelope,eventVersion:2});}catch{unsupported=true;}check('malformed envelope rejected safely',malformed);check('unsupported event version rejected safely',unsupported);
 await pool.query(`CREATE FUNCTION medorbit.s7_force_consumer_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.consumer_name=$q$${marker}-crash$q$ THEN RAISE EXCEPTION 'controlled consumer crash'; END IF; RETURN NEW; END $$; CREATE TRIGGER s7_force_consumer_failure BEFORE INSERT ON medorbit.processed_events FOR EACH ROW EXECUTE FUNCTION medorbit.s7_force_consumer_failure()`);
 const crashEnvelope={...envelope,eventId:crypto.randomUUID()};processedIds.push(crashEnvelope.eventId);let consumerCrashed=false;try{await observeEvent(`${marker}-crash`,crashEnvelope,pool);}catch{consumerCrashed=true;}check('consumer crash leaves no partial processed marker',consumerCrashed&&Number((await pool.query(`SELECT count(*) FROM medorbit.processed_events WHERE event_id=$1`,[crashEnvelope.eventId])).rows[0].count)===0);await pool.query('DROP TRIGGER s7_force_consumer_failure ON medorbit.processed_events; DROP FUNCTION medorbit.s7_force_consumer_failure()');
 const clinicalBefore=Number((await pool.query(`SELECT count(*) FROM medorbit.medical_records`)).rows[0].count);check('observer consumer performs no clinical mutation',Number((await pool.query(`SELECT count(*) FROM medorbit.medical_records`)).rows[0].count)===clinicalBefore);

 const continuity=await txEvent({payload:{userId:patient.id,state:'committed'}}),down=new FakeProducer();down.fail=true;await new OutboxPublisher({pool,producer:down,workerId:`${marker}-down`,batchSize:1,maxAttempts:3}).runOnce();check('Kafka down does not rollback completed business state',(await pool.query(`SELECT first_name_en FROM medorbit.user_profiles WHERE user_id=$1`,[patient.id])).rows[0].first_name_en==='Committed');check('Kafka-down outbox remains retryable',(await pool.query(`SELECT status FROM medorbit.outbox_events WHERE id=$1`,[continuity.id])).rows[0].status==='failed');
 down.fail=false;await pool.query(`UPDATE medorbit.outbox_events SET available_at=NOW() WHERE id=$1`,[continuity.id]);await new OutboxPublisher({pool,producer:down,workerId:`${marker}-return`,batchSize:1}).runOnce();check('publisher recovery eventually publishes pending event',(await pool.query(`SELECT status FROM medorbit.outbox_events WHERE id=$1`,[continuity.id])).rows[0].status==='published');
 const health=await fetch(`${apiBase}/health`);check('backend HTTP remains functional independently of Kafka',health.status===200);
 await publisher.disconnect();check('publisher disconnects gracefully',!producer.connected);
 }catch(error){failed++;console.error('  ✗ suite error:',error.stack||error.message);}finally{await cleanup();const residual=(await pool.query(`SELECT
  (SELECT count(*) FROM medorbit.outbox_events WHERE id=ANY($1::uuid[]))::int outbox,
  (SELECT count(*) FROM medorbit.processed_events WHERE event_id=ANY($2::uuid[]))::int processed,
  (SELECT count(*) FROM medorbit.users WHERE id=ANY($3::uuid[]))::int users`,[outboxIds.length?outboxIds:[crypto.randomUUID()],processedIds.length?processedIds:[crypto.randomUUID()],users.length?users:[crypto.randomUUID()]])).rows[0];console.log(`S7 residual counts: ${JSON.stringify(residual)}`);check('S7 fixtures leave zero residual rows',Object.values(residual).every(value=>Number(value)===0));await pool.end();}
 console.log(`\nS7 event foundation: ${passed} passed, ${failed} failed`);process.exit(failed?1:0);
})();
