import 'package:flutter_test/flutter_test.dart';
import 'package:mobile/features/chatbot/models/chatbot_models.dart';

void main() {
  test('parses chatbot response with places doctors suggestions metadata and coordinates', () {
    final response = ChatMessageResponse.fromJson({
      'success': true,
      'data': {
        'conversationId': 'conversation-1',
        'reply': 'Please visit the nearest clinic.',
        'intent': 'find_clinic',
        'confidence': '0.91',
        'places': [
          {
            'id': 42,
            'name_ar': 'عيادة نابلس',
            'name_en': 'Nablus Clinic',
            'latitude': '32.2211',
            'longitude': 35.2544,
            'distance_km': '1.7',
            'metadata': {'latitude': '32.2211', 'longitude': '35.2544', 'triage': 'urgent'},
            'unknown_place_field': 'preserved',
          },
        ],
        'clinics': [
          {'id': 'clinic-2', 'nameEn': 'Village Clinic'},
        ],
        'doctors': [
          {
            'id': 'doctor-1',
            'first_name_en': 'Mariam',
            'last_name_en': 'Saleh',
            'averageRating': '4.8',
            'consultation_fee': '70.5',
            'unknown_doctor_field': {'kept': true},
          },
        ],
        'route': {'distanceKm': '2.4', 'duration_minutes': '9', 'mode': 'driving'},
        'suggestions': [
          {'id': 's1', 'text': 'Show nearby clinics', 'metadata': {'source': 'triage'}},
        ],
        'unknown_response_field': 'preserved',
      },
      'message': 'ok',
    });

    expect(response.conversationId, 'conversation-1');
    expect(response.confidence, 0.91);
    expect(response.places.single.id, '42');
    expect(response.places.single.latitude, 32.2211);
    expect(response.places.single.metadata.latitude, 32.2211);
    expect(response.places.single.extra['unknown_place_field'], 'preserved');
    expect(response.clinics.single.nameEn, 'Village Clinic');
    expect(response.doctors.single.averageRating, 4.8);
    expect(response.doctors.single.extra['unknown_doctor_field'], {'kept': true});
    expect(response.route?.distanceKm, 2.4);
    expect(response.route?.extra['mode'], 'driving');
    expect(response.suggestions.single.metadata.values['source'], 'triage');
    expect(response.extra['unknown_response_field'], 'preserved');
  });

  test('parses conversation detail with messages saved places metadata and messageCount', () {
    final detail = ConversationDetail.fromJson({
      'data': {
        'conversation': {
          'id': 'conversation-1',
          'title': 'Headache advice',
          'is_auto_generated': true,
          'message_count': '2',
          'lastIntent': 'symptom_check',
          'hasLocation': 'true',
        },
        'messages': [
          {
            'id': 'message-1',
            'conversation_id': 'conversation-1',
            'message_text': 'I have a headache',
            'message_type': 'user',
            'confidence_score': '0.77',
            'metadata': {'latitude': 32.2, 'longitude': '35.2', 'device': 'mobile'},
            'entities': {'symptom': 'headache'},
            'conversationContext': {'last_question': 'pain level'},
            'created_at': '2026-08-04T10:00:00Z',
            'unknown_message_field': 'preserved',
          },
        ],
        'places': [
          {'id': 'place-1', 'name_en': 'Saved Clinic', 'distanceKm': '3.2'},
        ],
        'messageCount': 1,
      },
    });

    expect(detail.conversation?.isAutoGenerated, isTrue);
    expect(detail.conversation?.messageCount, 2);
    expect(detail.conversation?.hasLocation, isTrue);
    expect(detail.messages.single.confidenceScore, 0.77);
    expect(detail.messages.single.metadata.longitude, 35.2);
    expect(detail.messages.single.entities['symptom'], 'headache');
    expect(detail.messages.single.conversationContext['last_question'], 'pain level');
    expect(detail.messages.single.createdAt, isNotNull);
    expect(detail.messages.single.extra['unknown_message_field'], 'preserved');
    expect(detail.places.single.distanceKm, 3.2);
    expect(detail.messageCount, 1);
  });

  test('missing optional fields do not throw and toJson copies unknown metadata', () {
    expect(() => ChatMessageResponse.fromJson({'data': {}}), returnsNormally);

    final metadataSource = {'nested': {'value': 'kept'}};
    final metadata = ChatMetadata.fromJson(metadataSource);
    final json = metadata.toJson();

    (json['nested'] as Map)['value'] = 'changed';

    expect(metadata.values['nested'], {'value': 'kept'});
  });
}
