import 'dart:async';
import 'package:flutter/material.dart'; import 'package:flutter_riverpod/flutter_riverpod.dart'; import 'package:go_router/go_router.dart';
import '../../../core/theme/app_theme.dart'; import '../../../routes/route_paths.dart'; import '../../../shared/widgets/app_scaffold.dart'; import '../../../shared/widgets/app_text_field.dart'; import '../../../shared/widgets/empty_state.dart'; import '../../../shared/widgets/error_retry_state.dart'; import '../../../shared/widgets/primary_button.dart';
import '../models/chatbot_models.dart'; import '../providers/chatbot_provider.dart'; import '../providers/conversations_provider.dart'; import '../widgets/conversation_list_item.dart';

class ConversationsScreen extends ConsumerStatefulWidget { const ConversationsScreen({super.key}); @override ConsumerState<ConversationsScreen> createState() => _ConversationsScreenState(); }
class _ConversationsScreenState extends ConsumerState<ConversationsScreen> { final _search = TextEditingController(); Timer? _debounce;
// Blocks a second tap while `_open` is awaiting its load, which would push the
// same route twice and trip the Navigator's `!keyReservation.contains(key)`.
bool _isNavigating = false;
@override void initState() { super.initState(); WidgetsBinding.instance.addPostFrameCallback((_) => ref.read(conversationsControllerProvider.notifier).loadConversations()); }
@override void dispose() { _debounce?.cancel(); _search.dispose(); super.dispose(); }
@override Widget build(BuildContext context) { final state = ref.watch(conversationsControllerProvider); return AppScaffold(appBar: AppBar(title: const Text('Conversation history'), actions: [IconButton(tooltip: 'New conversation', onPressed: _newConversation, icon: const Icon(Icons.add_rounded))]), useSafeArea: true, keyboardAware: true, body: RefreshIndicator(onRefresh: () => ref.read(conversationsControllerProvider.notifier).loadConversations(), child: ListView(physics: const AlwaysScrollableScrollPhysics(), padding: const EdgeInsets.all(AppTheme.spaceMd), children: [AppTextField(label: 'Search conversations', controller: _search, prefixIcon: const Icon(Icons.search_rounded), onChanged: _onSearch), const SizedBox(height: AppTheme.spaceMd), if (state.isLoading || state.isSearching) const Center(child: Padding(padding: EdgeInsets.all(24), child: CircularProgressIndicator())) else if (state.error != null) ErrorRetryState(title: 'Could not load conversations', message: state.error!.message, retryLabel: 'Retry', onRetry: () => ref.read(conversationsControllerProvider.notifier).loadConversations(), variant: ErrorRetryVariant.compact) else if (state.conversations.isEmpty) const EmptyState(icon: Icons.history_outlined, title: 'No conversations yet', hint: 'Start a medical chat when you are ready.', variant: EmptyStateVariant.compact) else ...[for (final conversation in state.conversations) ConversationListItem(conversation: conversation, selected: conversation.id == state.selectedConversationId, onOpen: () => _open(conversation), onRename: () => _rename(conversation), onDelete: () => _delete(conversation)), if (state.canLoadMore) PrimaryButton(label: 'Load more', isLoading: state.isLoadingMore, onPressed: () => ref.read(conversationsControllerProvider.notifier).loadMore())]]))); }
void _onSearch(String value) { _debounce?.cancel(); _debounce = Timer(const Duration(milliseconds: 400), () { final query = value.trim(); if (query.length < 2) { if (query.isEmpty) ref.read(conversationsControllerProvider.notifier).loadConversations(); return; } ref.read(conversationsControllerProvider.notifier).searchConversations(query); }); }
Future<void> _open(ConversationSummary item) async { if (_isNavigating) return; _isNavigating = true; try { ref.read(conversationsControllerProvider.notifier).selectConversation(item.id); await ref.read(chatbotControllerProvider.notifier).loadConversation(item.id); if (mounted) await context.push(RoutePaths.chatbotConversationPath(item.id)); } finally { if (mounted) _isNavigating = false; } }
Future<void> _newConversation() async { ref.read(chatbotControllerProvider.notifier).startNewConversation(); ref.read(conversationsControllerProvider.notifier).selectConversation(null); if (mounted) context.push(RoutePaths.chatbot); }
Future<void> _rename(ConversationSummary item) async { final controller = TextEditingController(text: item.title); final title = await showDialog<String>(context: context, builder: (context) => AlertDialog(title: const Text('Rename conversation'), content: TextField(controller: controller, autofocus: true), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), TextButton(onPressed: () => Navigator.pop(context, controller.text.trim()), child: const Text('Save'))])); controller.dispose(); if (title?.isNotEmpty == true) await ref.read(conversationsControllerProvider.notifier).renameConversation(item.id, title: title!); }
Future<void> _delete(ConversationSummary item) async { final confirmed = await showDialog<bool>(context: context, builder: (context) => AlertDialog(title: const Text('Delete conversation?'), content: const Text('This cannot be undone.'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Cancel')), TextButton(onPressed: () => Navigator.pop(context, true), child: const Text('Delete'))])); if (confirmed == true) { final ok = await ref.read(conversationsControllerProvider.notifier).deleteConversation(item.id); if (ok && ref.read(chatbotControllerProvider).currentConversationId == item.id) ref.read(chatbotControllerProvider.notifier).startNewConversation(); } }
}
