BEGIN;


ALTER TABLE public.user_profiles
ADD COLUMN IF NOT EXISTS avatar_url TEXT;


ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;


ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS preferences JSONB DEFAULT '{}'::jsonb;


COMMIT;
